

def find_motif(string, motif):
    if len(motif) > len(string):
        raise Exception("mitif cant be longer than string")

    found_indicies = []
    motif_list = list(motif)
    string_list = list(string)
    for index in range(len(string_list)):
        if (len(string_list) - index) < len(motif_list):
            break
        if string_list[index] == motif_list[0]:
            if string_list[index : index + len(motif_list)] == motif_list:
                found_indicies.append(index + 1)

    print(str(found_indicies).replace(',', ''))




if __name__ == '__main__':
    find_motif('TATAGATACAGCGATACAGGATACAGGATACAGGATACAGCGAAGATACAGAGATACAGGATACAGGATACAGAATCAGATACAGGCCGATACAGTGAAAGCTCGATACAGCACCGATACAGGATACAGGTTTGCGATACAGGAACGGAGATACAGGATACAGTAGCGCCAAACGATACAGGGATACAGTCCCCAGGATACAGCGATACAGGATACAGTGCGGGGATACAGCAGATACAGAAACGATACAGCGCGGATACAGTTCACGATACAGCATCGATACAGGATACAGGGATACAGCAGGCAATGCTAGATACAGAGAGATACAGGATACAGAAGGATACAGGGTGATACAGAAGATACAGAGAGATACAGATTAAAAGATACAGTTGATACAGGATGATACAGAGCGATACAGATTGATACAGGATACAGGATACAGCTTCCGATACAGCCTGCAGATATCGAGATACAGGATACAGAGGGATACAGTCTTGATACAGTGGATACAGAGATACAGGGATACAGGCTGGATACAGGCCCTGGATACAGTATGGATACAGATGATACAGGCCGGATACAGCTTGGATACAGTGCTGGAACCGACCGATACAGTGATACAGAGATACAGCCGGGATACAGTTATGATACAGTTGAGATACAGGATACAGGGATACAGTCGATACAGACGATACAGTACCGATACAGGTCTAGATACAGGATACAGTGATACAGATGATACAGTCCGATACAGCCCTGATACAGGGTCTACAGATACAGGGACGATACAGGATACAGAAGATACAGAGTTGAGATACAGGATACAGGATACAGAGGCATCCTGTGATACAGTGATACAGGATACAGGATCAC',
               'GATACAGGA')
    # t1 = list('GATATATGCATATACTT')
    # t2 = list('ATAT')
    # print(t1[1:len(t2) + 1])